Вправа 1
Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [1]:
def task_1a():
    n = int(input("Enter n: "))
    arr = [[0 for j in range(n)] for i in range(n)]
    
    for i in range(n):
        arr[i][i] = i + 1

    for row in arr:
        print(row)
        
        
%time task_1a()

Enter n:  4


[1, 0, 0, 0]
[0, 2, 0, 0]
[0, 0, 3, 0]
[0, 0, 0, 4]
CPU times: user 23.9 ms, sys: 12.7 ms, total: 36.6 ms
Wall time: 2.74 s


In [2]:
import numpy as np

def task_1():
    n = int(input("Enter n: "))
    arr = np.zeros((n, n), dtype=int)
    arr[np.diag_indices_from(arr)] = np.arange(1, n+1)
    print(arr)


%time task_1()

Enter n:  4


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
CPU times: user 707 ms, sys: 499 ms, total: 1.21 s
Wall time: 1.3 s


In [6]:
def task_3a():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    r = int(input("Enter r: "))
    c = int(input("Enter c: "))
    
    arr = [[1 for j in range(m)] for i in range(n)]
    
    for i in range(n):
        if i % r == 0:
            arr[i] = [0 for j in range(m)]

    for i in range(m):
        if i % c == 0:
            for j in range(n):
                arr[j][i] = 0
        
    for row in arr:
        print(row)
        
%time task_3a()

Enter n:  6
Enter m:  7
Enter r:  2
Enter c:  3


[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 1, 1, 0]
CPU times: user 67.2 ms, sys: 59 ms, total: 126 ms
Wall time: 7.83 s


In [7]:
import numpy as np

def task_3b():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    r = int(input("Enter r: "))
    c = int(input("Enter c: "))
    
    arr = np.ones((n, m), dtype=int)
    arr[::r, :] = 0
    arr[:, ::c] = 0

    print(arr)
    
%time task_3b()

Enter n:  6
Enter m:  7
Enter r:  2
Enter c:  3


[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
CPU times: user 40.8 ms, sys: 29.6 ms, total: 70.4 ms
Wall time: 4.55 s


In [9]:
def task_4a():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = [[0 for j in range(n)] for i in range(m)]
    
    for i in range(n):
        arr[0][i] = i
        
    for row in arr:
        print(row)
        
%time task_4a()

Enter n:  3
Enter m:  4


[0, 1, 2]
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]
CPU times: user 17.6 ms, sys: 10.3 ms, total: 27.9 ms
Wall time: 1.75 s


In [12]:
import numpy as np

def task_4b():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = np.zeros((m, n), dtype=int)
    
    arr[0] = np.arange(n)
    
    print(arr)
    
%time task_4b()

Enter n:  3
Enter m:  4


[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
CPU times: user 20.2 ms, sys: 10.9 ms, total: 31.1 ms
Wall time: 1.95 s


In [15]:

def task_5a():
    n = int(input("Enter n: "))
    
    arr = [[0 for j in range(n)] for i in range(n)]
    
    for i in range(n):
        if i % 2 == 0:
            for j in range(n):
                arr[i][j] = 1
                
    for row in arr:
        print(row)
        
%time task_5a()

Enter n:  5


[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 1]
CPU times: user 29.8 ms, sys: 17.6 ms, total: 47.5 ms
Wall time: 3.63 s


In [16]:

import numpy as np

def task_5b():
    n = int(input("Enter n: "))
    
    arr = np.zeros((n, n), dtype=int)
    arr[::2] = np.ones(n, dtype=int)
    
    print(arr)
    
%time task_5b()

Enter n:  5


[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]
CPU times: user 10.2 ms, sys: 9.46 ms, total: 19.7 ms
Wall time: 1.06 s


In [ ]:
Вправа 10
Вводиться числа n i m. Створити масив випадкових значень n×m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне
відхилення, округлене до 3 знаків після коми.

In [19]:
import random
import math

def task_10a():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = [[round(random.uniform(0, 1), 3) for j in range(m)] for i in range(n)]

    arr_min = min(min(arr[i]) for i in range(n))
    arr_max = max(max(arr[i]) for i in range(n))

    sum_val = sum(sum(arr[i]) for i in range(n))
    arr_mean = sum_val / (n * m)

    sq_diff = sum((arr[i][j] - arr_mean) ** 2 for i in range(n) for j in range(m))
    arr_std = math.sqrt(sq_diff / (n * m))

    print(f"мінімум: {arr_min:.3f}")
    print(f"максимум: {arr_max:.3f}")
    print(f"середнє: {arr_mean:.3f}")
    print(f"дисперсія: {arr_std:.3f}")

%time task_10a()

Enter n:  4
Enter m:  5


мінімум: 0.028
максимум: 0.965
середнє: 0.554
дисперсія: 0.329
CPU times: user 23.7 ms, sys: 13.3 ms, total: 37 ms
Wall time: 2.68 s


In [21]:

import random
import math
import numpy as np

def task_10b():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = np.random.rand(n, m)
    arr_min = np.min(arr)
    arr_max = np.max(arr)
    arr_mean = np.mean(arr)
    arr_std = np.std(arr)
    
    print(f"мінімум: {arr_min:.3f}")
    print(f"максимум: {arr_max:.3f}")
    print(f"середнє: {arr_mean:.3f}")
    print(f"дисперсія: {arr_std:.3f}")
    
%time task_10b()    

Enter n:  4
Enter m:  5


мінімум: 0.006
максимум: 0.974
середнє: 0.554
дисперсія: 0.353
CPU times: user 17 ms, sys: 14.9 ms, total: 31.9 ms
Wall time: 1.67 s


In [22]:
def task_12a():
    n = int(input("Enter n: "))
    
    arr = [[1 for j in range(n)] for i in range(n)]
    
    arr[0] = [0 for i in range(n)]
    arr[n-1] = [0 for i in range(n)]
    
    for i in range(1, n-1):
        for j in range(n):
            if j == 0 or j == n - 1:
                arr[i][j] = 0
                
    for row in arr:
        print(row)
        
%time task_12a()

Enter n:  4


[0, 0, 0, 0]
[0, 1, 1, 0]
[0, 1, 1, 0]
[0, 0, 0, 0]
CPU times: user 13.2 ms, sys: 8.2 ms, total: 21.4 ms
Wall time: 1.42 s


In [23]:
import numpy as np

def task_12b():
    n = int(input("Enter n: "))
    
    arr = np.ones((n, n), dtype=int)
    
    arr[::n-1, :] = 0
    arr[:, ::n-1] = 0

    print(arr)
    
%time task_12b()

Enter n:  4


[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]
CPU times: user 28.4 ms, sys: 26 ms, total: 54.4 ms
Wall time: 4.94 s


In [ ]:
Вправа 16
Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями.

In [24]:
def task_16a():
    n = int(input("Enter n: "))
    
    arr = [i for i in range(n+1)]
    
    for i in range(n+1):
        if n/4 < i and i < 3*n/4:
            arr[i] = 0
            
    print(arr)
        
%time task_16a()

Enter n:  10


[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]
CPU times: user 103 ms, sys: 70.7 ms, total: 174 ms
Wall time: 17.1 s


In [25]:
import numpy as np

def task_16b():
    n = int(input("Enter n: "))
    
    arr = np.arange(n+1)
    arr[(arr > n/4) & (arr < 3*n/4)] = 0
    
    print(arr)
    
%time task_16b()

Enter n:  10


[ 0  1  2  0  0  0  0  0  8  9 10]
CPU times: user 10.6 ms, sys: 12.6 ms, total: 23.2 ms
Wall time: 1.44 s


In [ ]:
Вправа 17
Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значень, що менші за n/2 та більші за 3n/4 на протилежні.

In [26]:
def task_17a():
    n = int(input("Enter n: "))
    
    arr = [i for i in range(n+1)]
    
    for i in range(n+1):
        if i < n/2 or i > 3*n/4:
            arr[i] *= -1
            
    print(arr)
        
%time task_17a()

Enter n:  10


[0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10]
CPU times: user 156 ms, sys: 115 ms, total: 271 ms
Wall time: 26.3 s


In [27]:
import numpy as np

def task_17b():
    n = int(input("Enter n: "))
    
    arr = np.arange(n+1)
    arr[(arr < n/2) | (arr > 3*n/4)] *= -1
    
    print(arr)
    
%time task_17b()

Enter n:  10


[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]
CPU times: user 12.3 ms, sys: 9.64 ms, total: 21.9 ms
Wall time: 1.65 s


In [ ]:
Вправа 21
Ввести числа n і m. Згенерувати матрицю n×n випадкових цілих елементів з діапазону [0, m]. 
Замінити всі максимальні елементи цієї матриці на протилежні за знаком.

In [28]:
def task_21a():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = [[random.randint(0, m) for j in range(n)] for i in range(n)]
    
    print('Початковий вектор')
    for row in arr:
        print(row)
        
    arr_max = max(max(arr[i]) for i in range(n))
    for i in range(n):
        for j in range(n):
            if arr[i][j] == arr_max:
                arr[i][j] *= -1
                
    print('Змінений вектор')
    for row in arr:
        print(row)
        
%time task_21a()

Enter n:  4
Enter m:  10


Початковий вектор
[5, 2, 5, 5]
[4, 4, 2, 7]
[10, 5, 1, 2]
[7, 2, 5, 9]
Змінений вектор
[5, 2, 5, 5]
[4, 4, 2, 7]
[-10, 5, 1, 2]
[7, 2, 5, 9]
CPU times: user 42.5 ms, sys: 28.9 ms, total: 71.4 ms
Wall time: 6.81 s


In [29]:
import numpy as np

def task_21b():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = np.random.randint(0, m+1, size=(n, n))
    
    print('Початковий вектор')
    print(arr)
        
    arr_max = np.max(arr)
    
    arr[arr == arr_max] *= -1
                
    print('Змінений вектор')
    print(arr)
        
%time task_21b()

Enter n:  4
Enter m:  10


Початковий вектор
[[ 4  3  1  4]
 [ 4  5  7  2]
 [ 8  0  6  9]
 [ 2  8 10  6]]
Змінений вектор
[[  4   3   1   4]
 [  4   5   7   2]
 [  8   0   6   9]
 [  2   8 -10   6]]
CPU times: user 46.6 ms, sys: 32.6 ms, total: 79.3 ms
Wall time: 7.4 s


In [ ]:
Завдання 2
Розв'язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:

матричного множення;
оберненої матриці;
функції numpy.linalg.solve().
Порівняти всі рішення за допомогою функції numpy.allclose().

Матричне представлення системи лінійних алгебраїчних рівнянь та розв'язок:


In [30]:
A = [[2, -1, 3, 2],
    [3,  3,  3, 2],
    [3, -1, -1, 2],
    [3, -1, 3, -1]]

B = [4, 6, 6, 6]

S = [2, 0, 0, 0]

print('Матриця коефіцієнтів')
for row in A:
    print(row)
    
print('\nВектор вільних членів')
print(B)


print("\nВектор розв'язку")
print(S)

Матриця коефіцієнтів
[2, -1, 3, 2]
[3, 3, 3, 2]
[3, -1, -1, 2]
[3, -1, 3, -1]

Вектор вільних членів
[4, 6, 6, 6]

Вектор розв'язку
[2, 0, 0, 0]


In [ ]:
Перевірка

Спосіб 1: матричне множення

In [31]:
A = [[2, -1, 3, 2],
    [3,  3,  3, 2],
    [3, -1, -1, 2],
    [3, -1, 3, -1]]

B = [4, 6, 6, 6]

S = [2, 0, 0, 0]

fact_sol = [0] * 4

for i in range(4):
    sum = 0
    for j in range(4):
        sum += A[i][j] * S[j]
    fact_sol[i] = sum
    
print("А * S:")
print(fact_sol)

print("\nA * S == B:")
print(fact_sol == B)

А * S:
[4, 6, 6, 6]

A * S == B:
True


In [32]:
import numpy as np

A = np.array([[2, -1, 3, 2],
    [3,  3,  3, 2],
    [3, -1, -1, 2],
    [3, -1, 3, -1]])

B = np.array([4, 6, 6, 6])
S = np.array([2, 0, 0, 0])

A_inv = np.linalg.inv(A)


print("inverse A:")
print(A_inv)

fact_sol = A_inv.dot(B)

print("\nA_inv * B:")
print(fact_sol)

print("\nnp.allclose(S, fact_sol):")
print(np.allclose(S, fact_sol))

inverse A:
[[-0.18181818  0.06818182  0.20454545  0.18181818]
 [-0.20454545  0.23295455 -0.05113636 -0.04545455]
 [ 0.20454545  0.01704545 -0.19886364  0.04545455]
 [ 0.27272727  0.02272727  0.06818182 -0.27272727]]

A_inv * B:
[2.00000000e+00 0.00000000e+00 5.55111512e-17 2.22044605e-16]

np.allclose(S, fact_sol):
True


In [33]:
import numpy as np

A = np.array([[2, -1, 3, 2],
    [3,  3,  3, 2],
    [3, -1, -1, 2],
    [3, -1, 3, -1]])

B = np.array([4, 6, 6, 6])
S = np.array([2, 0, 0, 0])

fact_sol = np.linalg.solve(A, B)


print("np.linarg.solve(A,B):")
print(fact_sol)

print("\nnp.allclose(S, fact_sol):")
print(np.allclose(S, fact_sol))

np.linarg.solve(A,B):
[ 2.00000000e+00 -4.54182146e-17  4.54182146e-17  6.05576195e-17]

np.allclose(S, fact_sol):
True


In [34]:
import numpy as np

def task_3():
    A = np.array([[3, 2, -5], [4, 2, 0], [1, 1, 2]])
    B = np.array([[-1, 2, 4], [0, 3, 2], [-1, -3, 4]])

    # (A - B)A + 3B
    C = np.add(np.subtract(A, B).dot(A), np.multiply(B, 3))

    print("A:")
    print(A)
    print("\nB:")
    print(B)
    print("\n(A - B)A + 3B:")
    print(C)

%time task_3()

A:
[[ 3  2 -5]
 [ 4  2  0]
 [ 1  1  2]]

B:
[[-1  2  4]
 [ 0  3  2]
 [-1 -3  4]]

(A - B)A + 3B:
[[  0   5 -26]
 [  6  13 -18]
 [ 17   1  -2]]
CPU times: user 456 µs, sys: 782 µs, total: 1.24 ms
Wall time: 1.6 ms
